### PR TITLE
schema work

### PR DESCRIPTION
**Pull request by mzargham**
work on the ExtIP statuses. Plus I added a data model diagram for the ontology described in ExtIP 1. Looking for @ipatka to review that the image actual appears when the website for the ExtIPs is generated.

### CODE REVIEW

**Comment by mzargham** [comment]
@ipatka it does not seem like it compiles to the site preview. looking for suggestions on how to get it to show up.

**Comment by ipatka** [comment]
> 

The deploy preview link works for me https://deploy-preview-1--extitute.netlify.app/eips/eip-1

**Comment by ipatka** [comment]
oh the image. let me check

**Comment by ipatka** [comment]
fixed and reverted the eip to extip in table headers because it broke automation/ layout rendering

**Pull request merged**
